name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - php-version: '8.0'
            coverage: 'true'
            phpunit-version: '9'
          - php-version: '8.1'
            coverage: 'true'
            phpunit-version: '9'
          - php-version: '8.2'
            coverage: 'true'
            phpunit-version: '10'

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        ini-values: post_max_size=256M, max_execution_time=180
        extensions: mbstring, intl, calendar
        coverage: xdebug
        tools: php-cs-fixer, phpunit:${{ matrix.phpunit-version }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run Tests
      run: ./vendor/bin/phpunit

    - name: Code coverage
      if: ${{ matrix.coverage == 'true' }}
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./build/logs/codecov.xml
